AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CognitoDomain:
    Type: String
    MinLength: 3
    MaxLength: 63
  HostedZoneId:
    Description: Hosted Zone ID
    Type: String
  EmailSourceArn:
    Description: Email Source ARN
    Type: String
  CertificateArn:
    Description: Certificate ARN
    Type: String

Resources:

  CertificateManagerCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref CognitoDomain
      SubjectAlternativeNames:
        - !Sub "www.${CognitoDomain}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref CognitoDomain
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "www.${CognitoDomain}"
          HostedZoneId: !Ref HostedZoneId

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${CognitoDomain}-user-pool
      AutoVerifiedAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      UsernameAttributes:
        - email
      DeviceConfiguration:
        DeviceOnlyRememberedOnUserPrompt: true
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomain
      UserPoolId: !Ref UserPool
      CustomDomainConfig:
        CertificateArn: !Ref CertificateManagerCertificate

  WebUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: TekCapsuleWeb
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:4200
        - https://www.dev.tekcapsule.com
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO

Outputs:
  CognitoUserPoolID:
    Value: !Ref UserPool
    Description: The UserPool ID
  CognitoAppClientID:
    Value: !Ref WebUserPoolClient
    Description: TekCapsule Web Client
  HostedUIURL:
    Value: !Sub https://${CognitoDomain}.auth.us-west-2.amazoncognito.com/login?client_id=${WebUserPoolClient}&response_type=code&scope=email+openid+phone+profile&redirect_uri=https://dev.tekcapsule.com
    Description: The hosted UI URL
